### ISSUE TITLE
Can the item crafted only be a Player Head, or a Mob Skull/Head

### ISSUE THREAD

**Issue by Swaggggy** [Kikisito/GoldenHeads#1]
This works very well and is easily configurable! I just had 1 problem and I'm not if it's me making a mistake or me misunderstanding. Is it possible for the Golden head, to not be a head or mob head/skull after crafting? I've gone to the website listed and used the proper names for items, and when I put them in the crafting recipe doesn't work. Only player heads and mob heads/skulls work. I want to use a custom texture that isn't a player head and it would be easier to re-texture an item to my liking compared to the skulls/heads. Thanks in advance for the help!
![nether_star 2](https://user-images.githubusercontent.com/86086886/122490246-902c9780-cfaf-11eb-99f2-8be847411cc3.PNG)
![nether_star](https://user-images.githubusercontent.com/86086886/122490247-902c9780-cfaf-11eb-9e2a-c40253be8683.PNG)

**Comment by Kikisito** [comment]
Hi. I've just found what's causing the issue, so I'll be releasing a new version fixing this as soon as I can. Thanks for reporting it.

**Comment by Kikisito** [comment]
Hi. I'm checking the issue. I'll tell you more as soon as I can.

**Comment by Kikisito** [comment]
Does any error appear in your console log? I think I have found the issue but I want to be sure

**Comment by Kikisito** [comment]
Hello again. I think the issue got fixed in the last release ([click here](https://github.com/Kikisito/GoldenHeads/releases/tag/1.0.3)). Could you please confirm that everything works correctly now? Thanks!

**Comment by Swaggggy** [comment]
I can confirm it is working! Thank you for fixing this especially on such short notice! Many thanks
