### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by Brasil150** [Kikisito/GoldenHeads#11]
Hello, are there plans to add support for 1.21?

**Comment by Kikisito** [comment]
Hello. The plugin seems to work correctly for 1.21. What error are you getting?

**Comment by Kikisito** [comment]
Please, also specify the version you are using and your Spigot/Paper version

**Comment by Brasil150** [comment]
Hello, sorry for commenting on Spigot and here. I only saw support for 1.20 reported on the website.

And there were no commits here so I thought the plugin was abandoned. I'm actually having a problem with the plugin, I'm going to open a specialized issue.
