### ISSUE TITLE
Geyser and Nameless heads in Bedrock clients.

### ISSUE THREAD

**Issue by Brasil150** [Kikisito/GoldenHeads#12]
Hello, recently with the arrival of the new updates for 1.21, the players' names on their heads are not visible in Bedrock.

![a0b77ac9-94cc-4136-95e2-98a6f2740e57](https://github.com/user-attachments/assets/f269e229-b684-4d3e-8c8a-74a19e3e04d3)

The heads are still visible normally in Java Edition and when placed on the ground by Bedrock players.

The name is normally visible in Java Edition.. But Bedrock players don't see the names

**Comment by Reddishye** [comment]
Sorry, could you write the steps to replicate it? Are you saying that head data is not recognized by bedrock players?

**Comment by Reddishye** [comment]
[goldenheads-2.1.zip](https://github.com/user-attachments/files/16321205/goldenheads-2.1.zip)
try this build, it should trigger a warn on console telling you what to do

**Comment by Reddishye** [comment]
The version I sent you should trigger a warn on the console telling you what to do---------- Forwarded message ----------From: Brasil150 ***@***.***>Date: 20 Jul 2024 03:03Subject: [Kikisito/GoldenHeads] Geyser and Nameless heads in Bedrock clients. (Issue #12)To: Kikisito/GoldenHeads ***@***.***>Cc: Subscribed ***@***.***>
Hello, recently with the arrival of the new updates for 1.21, the players' names on their heads are not visible in Bedrock.
a0b77ac9-94cc-4136-95e2-98a6f2740e57.jpg (view on web)
The heads are still visible normally in Java Edition and when placed on the ground by Bedrock players.
But Bedrock players don't see the names

**Comment by Brasil150** [comment]
> Sorry, could you write the steps to replicate it? Are you saying that head data is not recognized by bedrock players?

Yes, that's pretty much it. When Bedrock Edition players have a head in their inventory, all they see is:

"Player head" with Steve's texture.

But if you place them on the ground, they will be visible to them normally.

If you place the same head in a Java player's inventory, they won't have this problem. They will be able to see the name of the head and the skin.

Sorry for the late reply, I didn't see the Github notifications. I'll be testing the file you sent me and get back to you! Thanks.

**Comment by Brasil150** [comment]
Test carried out, the problem continues and there are no warnings on the console.
