### ISSUE TITLE
Suggestion - Reload feature

### ISSUE THREAD

**Issue by BakProject** [Kikisito/GoldenHeads#4]
Hey there! Another suggestion for your plugin Golden Heads.

* I think a /goldenheads reload or /gh reload option would be fantastic for testing purposes while changing the config. So far I have not found a reload command so I have to restart my whole server just to test 1 setting I changed. This could be beneficial especially if players/owners are testing golden heads in a pvp perspective without having to restart the whole server.

This plugin is fantastic and works great, fast response and straight to the point on fixing issues.

**Comment by Kikisito** [comment]
The plugin is fully compatible with reload plugins as Plugman or ServerUtils. Anyways, I can try to introduce the reload subcommand. Thanks for your suggestion!

**Comment by Reddishye** [comment]
As I don't see Kikisito is going to do this, I'll take this one :)

**Comment by Kikisito** [comment]
Implemented by @Reddishye. Please see PR #6
