### ISSUE TITLE
Suggestion - Changing the crafting recipe

### ISSUE THREAD

**Issue by SkyTheNerd** [Kikisito/GoldenHeads#5]
I want to change the crafting recipe for the golden head, but it isn't an option. Could you add it?

**Comment by Kikisito** [comment]
I don't have much time right now. I'll do it asap.

**Comment by SkyTheNerd** [comment]
alright, thanks!

**Comment by Kikisito** [comment]
> alright, thanks!

It is in my to-do list, I didn't forget it! I'm just really busy with university these months :/

**Comment by Reddishye** [comment]
As I don't see Kikisito is going to do this, I'll take this one :)

**Comment by Reddishye** [comment]
Done
